export const FETCH_PRODUCTS= "FETCH_PRODUCTS";
export const FILTER_PRODUCTS_BY_TYPE_SIZE="FILTER_PRODUCTS_BY_TYPE_SIZE";
export const SORT_PRODUCTS="SORT_PRODUCTS";
export const ADD_TO_CART="ADD_TO_CART";
export const REMOVE_FROM_CART="REMOVE_FROM_CART";